networks:
  1panel-network:
    external: true

services:
  iframely:
    image: ghcr.io/pooneyy/iframely:2.5.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8061
    volumes:
      - ./config/config.local.js:/iframely/config.local.js
    environment:
      - NODE_ENV=production
      - PORT=8061
      - HOST=0.0.0.0
      - HTTPS_PROXY=${HTTP_PROXY}
