networks:
  1panel-network:
    external: true

services:
  tissue:
    image: chris2s/tissue:1.8.1
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:9193
    volumes:
      - ${TISSUE_ROOT_PATH}/config:/app/config
      - ${TISSUE_ROOT_PATH}/video:/data/video
      - ${TISSUE_ROOT_PATH}/file:/data/file
      - ${TISSUE_ROOT_PATH}/downloads:/downloads
    environment:
      - TZ=Asia/Shanghai
