services:
  vaultwarden:
    image: vaultwarden/server:1.34.3
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      DOMAIN: ${PANEL_VW_DOMAIN}
      ADMIN_TOKEN: ${PANEL_VW_ADMIN_TOKEN}
    volumes:
      - ./data:/data
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
