networks:
  1panel-network:
    external: true

services:
  umami:
    image: umamisoftware/umami:postgresql-v2.18.1
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    environment:
      - DISABLE_TELEMETRY = 1
      - REMOVE_TRAILING_SLASH = 1
      - DATABASE_TYPE=postgresql
      - DATABASE_URL=postgresql://username:password@${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE_NAME}
