services:
  picx:
    image: ghcr.io/pooneyy/picx:latest
    pull_policy: always
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - ${DATA_PATH}:/usr/share/nginx/html
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
