networks:
  1panel-network:
    external: true

services:
  nodepassdash:
    image: ghcr.io/nodepassproject/nodepassdash:3.2.7
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    volumes:
      - ${NODEPASSDASH_ROOT_PATH}/logs:/app/logs
      - ${NODEPASSDASH_ROOT_PATH}/public:/app/public
    environment:
      - TZ=Asia/Shanghai
      - PORT=${PANEL_APP_PORT_HTTP}
