services:
  filecodebox:
    image: lanol/filecodebox:2.2.1
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:12345"
    volumes:
      - "${DATA_PATH}:/app/data"
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
