services:
  als:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    environment:
      - HTTP_PORT=${PANEL_APP_PORT_HTTP}
    image: wikihostinc/looking-glass-server:latest
    pull_policy: always
    labels:
      createdBy: "Apps"

