networks:
  1panel-network:
    external: true

services:
  garage:
    image: dxflrs/garage:v2.0.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_S3_API}:3900
      - ${PANEL_APP_PORT_RPC}:3901
      - ${PANEL_APP_PORT_S3_WEB}:3902
      - ${PANEL_APP_PORT_API}:3903
    volumes:
      - ${GARAGE_ROOT_PATH}/config/garage.toml:/etc/garage.toml
      - ${GARAGE_ROOT_PATH}/meta:/var/lib/garage/meta
      - ${GARAGE_ROOT_PATH}/data:/var/lib/garage/data
    environment:
      - TZ=Asia/Shanghai
  garage-webui:
    image: khairul169/garage-webui:1.1.0
    container_name: ${CONTAINER_NAME}-web
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ${GARAGE_ROOT_PATH}/config/garage.toml:/etc/garage.toml
    ports:
      - ${PANEL_APP_PORT_HTTP}:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
