networks:
  1panel-network:
    external: true

services:
  kvrocks:
    image: apache/kvrocks:2.14.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6666
    volumes:
      - ${KVROCKS_ROOT_PATH}:/kvrocks_data
    environment:
      - TZ=Asia/Shanghai
