services:
  diun:
    container_name: ${CONTAINER_NAME}
    image: crazymax/diun:4.30.0
    command: serve
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data:/data
      - ./diun.yml:/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=Asia/Shanghai"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
networks:
  1panel-network:
    external: true 