networks:
  1panel-network:
    external: true

services:
  nexus3:
    image: sonatype/nexus3:3.87.1
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8081
    volumes:
      - ${NEXUS3_ROOT_PATH}/data:/nexus-data
    environment:
      - TZ=Asia/Shanghai
