services:
  wechat-selkies:
    image: nickrunning/wechat-selkies:0.0.6
    container_name: wechat-selkies
    volumes:
      - ${CONFIG_PATH}:/config
    # devices:
    #   - /dev/dri:/dev/dri # optional, for hardware acceleration
    ports:
      - ${PANEL_APP_PORT_HTTP}:3001
    restart: always
    environment:
      - PUID=1000
      - PGID=100
      - LC_ALL=zh_CN.UTF-8
      - AUTO_START_WECHAT=true
      - AUTO_START_QQ=false
      - CUSTOM_USER=${PANEL_USER}
      - PASSWORD=${PANEL_PASSWORD}
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true