networks:
  1panel-network:
    external: true

services:
  mx-server-shiro:
    image: innei/shiro:1.2.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:2323
    volumes:
      - ${MX_SERVER_SHIRO_ROOT_PATH}/public:/app/public
    environment:
      - TZ=Asia/Shanghai
      - NEXT_SHARP_PATH=/usr/local/lib/node_modules/sharp
