networks:
  1panel-network:
    external: true

services:
  stash-box:
    image: stashapp/stash-box:development
    pull_policy: always
    container_name: ${CONTAINER_NAME}
    labels:
      - createdBy=Apps
      - traefik.http.routers.stash-box.rule=Host(`<DOMAIN>`)
      - traefik.http.routers.stash-box.tls=true
      - traefik.http.routers.stash-box.tls.certresolver=stash-box
      - traefik.port=9998
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    volumes:
      - ${STASH_BOX_ROOT_PATH}/data:/root/.stash-box
    environment:
      - HTTPS_PROXY=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - NO_PROXY=${NO_PROXY:-}
