services:
  port-forward-agent:
    image: ghcr.io/pooneyy/port-forward:1.3.7-agent
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
      - "./data:/app/pfg/forward-agent/conf"
    cap_add:
      - NET_ADMIN
    labels:  
      createdBy: "Apps" 
