networks:
  1panel-network:
    external: true

services:
  apifox-runner:
    image: registry.cn-hangzhou.aliyuncs.com/apifox/self-hosted-general-runner:1.9.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:4524
    volumes:
      - ${APIFOX_RUNNER_ROOT_PATH}/runner:/opt/runner
    environment:
      - TZ=Asia/Shanghai
      - SERVER_APP_BASE_URL=${SERVER_APP_BASE_URL}
      - TEAM_ID=${TEAM_ID}
      - RUNNER_ID=${RUNNER_ID}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
