networks:
  1panel-network:
    external: true

services:
  dpanel:
    image: dpanel/dpanel:1.9.2
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_ADMIN}:8080
      - ${PANEL_APP_PORT_HTTP}:80
      - ${PANEL_APP_PORT_HTTPS}:443
    volumes:
      - ${DPANEL_ROOT_PATH}/data:/dpanel
      - ${DPANEL_ROOT_PATH}/compose:/dpanel/compose
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_NAME=${CONTAINER_NAME}
