networks:
  1panel-network:
    external: true

services:
  smtp_proxy_server:
    image: ghcr.io/dreamhunter2333/cloudflare_temp_email/smtp_proxy_server:v1.1.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_SMTP}:${PANEL_APP_PORT_SMTP}
      - ${PANEL_APP_PORT_IMAP}:${PANEL_APP_PORT_IMAP}
    environment:
      - TZ=Asia/Shanghai
      - proxy_url=${PROXY_URL}
      - port=${PANEL_APP_PORT_SMTP}
      - imap_port=${PANEL_APP_PORT_IMAP}
