networks:
  1panel-network:
    external: true

services:
  homarr:
    image: ghcr.io/ajnart/homarr:0.16.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    network_mode: ${NETWORK_MODE}
    ports:
      - ${PANEL_APP_PORT_HTTP}:7575
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMARR_ROOT_PATH}/configs:/app/data/configs
      - ${HOMARR_ROOT_PATH}/icons:/app/public/icons
      - ${HOMARR_ROOT_PATH}/data:/data
