services:
  homeassistant:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - "${DATA_PATH}:/config"
    environment:
      - TZ=Asia/Shanghai
    image: homeassistant/home-assistant:latest
    pull_policy: always
    labels:
      createdBy: "Apps"
