services:
  ddns-go:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - "${DATA_PATH}:/root"
    image: jeessy/ddns-go:latest
    pull_policy: always
    labels:
      createdBy: "Apps"
