services:
  oauth2_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.13.0
    container_name: ${CONTAINER_NAME}
    environment:
      - OAUTH2_PROXY_PROVIDER=${PANEL_OAUTH2_PROXY_PROVIDER}
      - OAUTH2_PROXY_CLIENT_ID=${PANEL_OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${PANEL_OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_REDIRECT_URL=${PANEL_OAUTH2_PROXY_REDIRECT_URL}
      - OAUTH2_PROXY_OIDC_ISSUER_URL=${PANEL_OAUTH2_PROXY_OIDC_ISSUER_URL}
      - OAUTH2_PROXY_COOKIE_SECRET=${PANEL_OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=${PANEL_OAUTH2_PROXY_EMAIL_DOMAINS}
      - OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=${PANEL_OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL}
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=${PANEL_OAUTH2_PROXY_CODE_CHALLENGE_METHOD}
      - OAUTH2_PROXY_REVERSE_PROXY=${PANEL_OAUTH2_PROXY_REVERSE_PROXY}
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
    ports:
      - "${PANEL_APP_PORT_HTTP}:4180"
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    restart: always

networks:
  1panel-network:
    external: true
