services:
  gh-proxy:
    image: wjqserver/ghproxy:4.3.1
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - ${DATA_PATH}/log:/data/ghproxy/log
      - ${DATA_PATH}/config:/data/ghproxy/config
    labels:  
      createdBy: "Apps"

networks:
  1panel-network:  
    external: true