networks:
  1panel-network:
    external: true

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    tty: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${PANEL_APP_PORT_HTTPS}:9200
      - ${PANEL_APP_PORT_CLUSTER}:9300
    volumes:
      - ${ELASTICSEARCH_ROOT_PATH}/data:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_ROOT_PATH}/backup:/usr/share/elasticsearch/backup
      - ${ELASTICSEARCH_ROOT_PATH}/plugins:/usr/share/elasticsearch/plugins
    environment:
      - LICENSE=basic
      - ES_SETTING_BOOTSTRAP_MEMORY__LOCK=true
      - ES_SETTING_PATH_REPO=/usr/share/elasticsearch/backup
