networks:
  1panel-network:
    external: true

services:
  syncthing_discosrv:
    container_name: ${CONTAINER_NAME}
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Shanghai
    image: syncthing/discosrv:2.0.0
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8443
    restart: always
    volumes:
      - ./data:/var/stdiscosrv
