networks:
  1panel-network:
    external: true

services:
  iyuuplus:
    image: iyuucn/iyuuplus:latest
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8780
      - ${PANEL_APP_PORT_IYUU:-}:8787
      - ${PANEL_APP_PORT_WS:-}:3131
    volumes:
      - ${IYUUCN_ROOT_PATH}/iyuu:/iyuu
      - ${IYUUCN_ROOT_PATH}/data:/data
      - ${IYUUCN_ROOT_PATH}/qBittorrent:/qBittorrent
      - ${IYUUCN_ROOT_PATH}/transmission:/transmission
      - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
      - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
      - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
