services:
  homeassistant:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - "${DATA_PATH}:/config"
    environment:
      - TZ=Asia/Shanghai
    image: homeassistant/home-assistant:2025.12.0.dev202511100241
    labels:  
      createdBy: "Apps"
