networks:
  1panel-network:
    external: true

services:
  ghost:
    image: ghost:6.10.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:2368
    volumes:
      - ${GHOST_ROOT_PATH}/data:/var/lib/ghost/content
    environment:
      - NODE_ENV=production
      - server__host=0.0.0.0
      - server__port=2368
      - database__client=mysql
      - mail__options__service=Email
      - mail__options__secure=true
      - url=${url}
      - admin__url=${admin__url}
      - database__connection__host=${database__connection__host}
      - database__connection__user=${database__connection__user}
      - database__connection__password=${database__connection__password}
      - database__connection__database=${database__connection__database}
