services:
  bililive-go:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${DATA_PATH}:/srv/bililive"
    image: chigusa/bililive-go:latest
    pull_policy: always
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
