services:
  verysync:
    image: jonnyan404/verysync:v2.21.3
    container_name: verysync
    environment:
      - PORT=${PANEL_APP_PORT_HTTP}
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
      - ${VERYSYNC_TRANSFER_PORT}:22330
      - ${PUBLIC_RELAY_PORT}:3000
      - ${LOCAL_AREA_NETWORK_UDP_DISCOVERY_PORT_1}:22027/udp
      - ${LOCAL_AREA_NETWORK_UDP_DISCOVERY_PORT_2}:22037/udp
    volumes:
      - ${VERYSYNC_DATA_PATH}:/data
    restart: always
    labels:  
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:  
  1panel-network:  
    external: true
