services:
  rathole:
    image: "rapiz1/rathole:latest"
    pull_policy: always
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - "${CONFIG_PATH}:/app/config.toml"
      - "./data/tls/:/app/tls/"
    command: --${SERVICE_MODE} /app/config.toml
    labels:
      createdBy: "Apps"
