services:
  lucky:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
      - ${DATA_PATH}:/goodluck
    image: gdy666/lucky:latest
    pull_policy: always
    labels:
      createdBy: "Apps"
