networks:
  1panel-network:
    external: true

services:
  napcat:
    image: mlikiowa/napcat-docker:v4.9.83
    container_name: napcat-${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_NAPCAT}:6099
    mac_address: ${NAPCAT_MAC_ADDRESS:-02:42:ac:11:00:02}
    volumes:
      - ${ASTRBOT_ROOT_PATH}/data:/AstrBot/data
      - ${ASTRBOT_ROOT_PATH}/ntqq:/app/.config/QQ
    environment:
      - TZ=Asia/Shanghai
      - MODE=astrbot
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
  astrbot:
    image: soulter/astrbot:v4.9.2
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6185
      - ${PANEL_APP_PORT_QQ_WH}:6199
      - ${PANEL_APP_PORT_QQ_API}:6196
      - ${PANEL_APP_PORT_WECOM}:6195
      - ${PANEL_APP_PORT_WECHAT}:11451
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ASTRBOT_ROOT_PATH}/data:/AstrBot/data
      - ${ASTRBOT_ROOT_PATH}/ntqq:/app/.config/QQ
      - ${ASTRBOT_ROOT_PATH}/napcat/config:/app/napcat/config
    environment:
      - TZ=Asia/Shanghai
